### ISSUE TITLE
errors occur when right clicking the mouse

### ISSUE THREAD

**Issue by fountainer** [randy3k/AlignTab#75]
When I right click the mouse, errors are printed in the console. When I disable this plugin, no error is printed. Windows 10. sublime text version:  3143. AligTab version: 2.1.8
```
Traceback (most recent call last):
  File "D:\software\Sublime Text 3\sublime_plugin.py", line 706, in is_enabled_
    raise ValueError("is_enabled must return a bool", self)
ValueError: ('is_enabled must return a bool', <AlignTab.table.AlignTabClearMode object at 0x0000024BB83D1F60>)
Traceback (most recent call last):
  File "D:\software\Sublime Text 3\sublime_plugin.py", line 706, in is_enabled_
    raise ValueError("is_enabled must return a bool", self)
ValueError: ('is_enabled must return a bool', <AlignTab.table.AlignTabClearMode object at 0x0000024BB83D1F60>)
Traceback (most recent call last):
  File "D:\software\Sublime Text 3\sublime_plugin.py", line 725, in is_visible_
    raise ValueError("is_visible must return a bool", self)
ValueError: ('is_visible must return a bool', <AlignTab.table.AlignTabClearMode object at 0x0000024BB83D1F60>)
```

**Comment by randy3k** [comment]
Thanks for the report. Fixed at 5b59a72.
